spring.application.name=risk-intelligence
spring.datasource.url=jdbc:postgresql://localhost:5432/esg_risk_intelligence
spring.datasource.username=esg_user
spring.datasource.password=esg_dev_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
